-- auto-generated by wall-theme
return {
  background = "rgba(14171aff)",
  backgroundAlt = "rgba(20242aff)",
  foreground = "rgba(ebedefff)",
  accent = "rgba(73deb8ff)",
  accent2 = "rgba(739ddeff)",
  accent3 = "rgba(73d0deff)",
}
